version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/warehouse
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: